### PR TITLE
Fix #61, #51

### LINKED ISSUE #61: Fix scoping
Lambdas among other things have broken scoping. Not completely sure what exactly so I'd recommend against merging before _thorough_ testing

### PR DESCRIPTION
**Pull request by somebody1234**
Might fix issues #61 and #51.

### CODE REVIEW

**Comment by ConorOBrien-Foxx** [comment]
So you've found that the bottleneck was the lexer? (In 99320fa) I assume that's why `\G`s were added to the RegExs.

**Comment by ConorOBrien-Foxx** [comment]
Also, is there a reason you chose a different color scheme for the output in the REPL than the scheme which colors the input?

image

**Comment by somebody1234** [comment]
@ConorOBrien-Foxx Well, the output currently displays as Ruby objects, making things consistent would be a very good idea but I'm not sure what would be the best way to do that

**Comment by somebody1234** [comment]
@ConorOBrien-Foxx Yeah, the bottleneck is still the lexer, looks like one way would be to combine the regexes (doable, but might be a bit messy)

**Pull request closed without merging**
