### PR TITLE
Implement #44, add more color

### PR DESCRIPTION
**Pull request by somebody1234**
Fixes issue #44.

### CODE REVIEW

**Comment by ConorOBrien-Foxx** [comment]
`-a` option looks nice.

`-A` is broken for lambdas, see: `attache -Ae "{_+2*3}"`

**Comment by somebody1234** [comment]
Should be fixed, but you might want to check again just to make sure

**Comment by somebody1234** [comment]
Wait... not fixed

**Comment by somebody1234** [comment]
Seems like it does print out the AST differently than before, not sure if this behavior is ok, or if maybe everything should be moved to `inspect`

**Comment by somebody1234** [comment]
This was a bit rushed, I think there might still be some things to make more consistent

**Pull request merged**
